name: Build SunamoGoogleMyMaps

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoGoogleMyMaps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGoogleMyMaps/SunamoGoogleMyMaps.csproj

    - name: Build
      run: dotnet build SunamoGoogleMyMaps/SunamoGoogleMyMaps.csproj --configuration Release --no-restore

  test:
    name: Test SunamoGoogleMyMaps.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGoogleMyMaps.Tests/SunamoGoogleMyMaps.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoGoogleMyMaps.Tests/SunamoGoogleMyMaps.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoGoogleMyMaps.Tests/SunamoGoogleMyMaps.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
